-- MySQL Script generated by MySQL Workbench
-- sáb 18 nov 2017 12:54:08 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema imc_control_crud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imc_control_crud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imc_control_crud` DEFAULT CHARACTER SET utf8 ;
USE `imc_control_crud` ;

-- -----------------------------------------------------
-- Table `imc_control_crud`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imc_control_crud`.`customers` (
  `idcustomers` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(45) NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`idcustomers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imc_control_crud`.`recordimc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imc_control_crud`.`recordimc` (
  `idrecordimc` INT(11) NOT NULL AUTO_INCREMENT,
  `height` FLOAT NULL,
  `weight` FLOAT NULL,
  `imc` FLOAT NULL,
  `category` VARCHAR(45) NULL,
  `daterecord` DATETIME NULL,
  `customers_idcustomers` INT(11) NOT NULL,
  PRIMARY KEY (`idrecordimc`),
  INDEX `fk_recordimc_customers_idx` (`customers_idcustomers` ASC),
  CONSTRAINT `fk_recordimc_customers`
    FOREIGN KEY (`customers_idcustomers`)
    REFERENCES `imc_control_crud`.`customers` (`idcustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
